kengz/openai_lab

main.py, rl/memory.py, rl/session.py, rl/spec.py, rl/state_preprocessing.py, rl/util.py
Session.py has the most major changes. All other changes are minor and don't majorly affect the logic.
=> State preprocessing

gulpfile.js
setup dropbox, change gulp file watcher
=> setup dropbox, change gulp file watcher

package.json, rl/asset/sess_specs.json, rl/experiment.py
Set things up to test the experimentation framework and plot at scale.
=> Experiment fix

package.json
add the missing `resolve-dir` dependency for gruntfile
=> add missing js dependency

rl/experiment.py
fix a small indexing error in session is_completed check
=> bug fix in session is_completed

Gruntfile.js, README.md, package.json, rl/agent/atari_conv_dqn.py, rl/experiment.py, rl/hyperoptimizer.py, rl/memory/ranked.py, rl/policy/boltzmann.py, rl/policy/epsilon_greedy.py, setup.py, test/test_rl.py
=> rename to OpenAI Lab and codacy fixes

Gruntfile.js
=> file sync dir fix

Gruntfile.js, config/example-default.json, config/keras.json, rl/agent/deep_sarsa.py, rl/agent/dqn_freeze.py, rl/agent/offpol_sarsa.py, rl/asset/experiment_specs.json, rl/asset/problems.json, rl/util.py
=> Codacy style fixes

Gruntfile.js, bin/setup, circle.yml, rl/analytics.py, rl/asset/experiment_specs.json, rl/experiment.py, rl/hyperoptimizer/base_hyperoptimizer.py
=> continue to fix slow memleak

rl/experiment.py
completely fix resume, tested on dev_dqn
=> Fix resume

.gitignore, Gruntfile.js, rl/agent/dqn_freeze.py, rl/analytics.py, rl/asset/experiment_specs.json, rl/experiment.py, rl/hyperoptimizer/base_hyperoptimizer.py, rl/util.py
(delay to the next PR)
- change all import structure to use the minimal scoping (dev anti-pattern, but fuck it, cuz python)
=> Fix history and slower memleak

circle.yml, rl/analytics.py, test/test_rl.py
=> correlation plots

rl/agent/conv_dqn.py, rl/agent/double_conv_dqn.py, rl/agent/double_dqn.py, rl/agent/dqn.py, rl/agent/dqn_freeze.py, rl/asset/experiment_specs.json, rl/experiment.py, rl/hyperoptimizer/base_hyperoptimizer.py, rl/hyperoptimizer/random_search.py, rl/memory/linear.py, rl/memory/ranked.py, rl/optimizer/adam.py, rl/optimizer/rmsprop.py, rl/optimizer/sgd.py, rl/util.py
=> Keras import containment, fixes

rl/hyperoptimizer/random_search.py
=> fix ideal_fitness_score

rl/agent/dqn_freeze.py, rl/asset/experiment_specs.json, rl/hyperoptimizer/base_hyperoptimizer.py, rl/policy/boltzmann.py
=> Misc fixes

rl/asset/experiment_specs.json, rl/asset/problems.json, rl/experiment.py, rl/hyperoptimizer/random_search.py
=> Experiment

rl/hyperoptimizer/random_search.py, rl/spec/classic_experiment_specs.json
=> schedule experiments

README.md, rl/agent/ddpg.py, rl/policy/noise.py, rl/spec/box2d_experiment_specs.json, rl/spec/classic_experiment_specs.json, rl/spec/dev_experiment_specs.json, rl/spec/problems.json, rl/util.py
=> Refactor and doc fix

rl/spec/classic_experiment_specs.json
[dqn-2017_03_19_004714_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/853865/dqn-2017_03_19_004714_analysis_data.csv.zip)
[dqn-2017_03_19_004714_t79.json.zip](https://github.com/kengz/openai_lab/files/853866/dqn-2017_03_19_004714_t79.json.zip)
=> Solution: CartPole-v0 with DQN

rl/analytics.py, rl/spec/classic_experiment_specs.json
=> DDPG fixes

rl/spec/box2d_experiment_specs.json, rl/spec/problems.json
=> schedule 2 lunar experiments

rl/spec/classic_experiment_specs.json
[double_dqn-2017_03_19_194335_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/856785/double_dqn-2017_03_19_194335_analysis_data.csv.zip)
[double_dqn-2017_03_19_194335_t59.json.zip](https://github.com/kengz/openai_lab/files/856786/double_dqn-2017_03_19_194335_t59.json.zip)
=> Solution: CartPole-v0 with double-DQN

rl/spec/classic_experiment_specs.json
[dqn_v1-2017_03_20_200957_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/861338/dqn_v1-2017_03_20_200957_analysis_data.csv.zip)
[dqn_v1-2017_03_20_200957_t61.json.zip](https://github.com/kengz/openai_lab/files/861333/dqn_v1-2017_03_20_200957_t61.json.zip)
=> Solution: CartPole-v1 with DQN

rl/spec/classic_experiment_specs.json
[double_dqn_v1-2017_03_22_021032_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/866838/double_dqn_v1-2017_03_22_021032_analysis_data.csv.zip)
[double_dqn_v1-2017_03_22_021032_t79.json.zip](https://github.com/kengz/openai_lab/files/866836/double_dqn_v1-2017_03_22_021032_t79.json.zip)
=> Solution: CartPole-v1 with double-DQN

rl/analytics.py, rl/spec/classic_experiment_specs.json
=> Schedule mountain and sarsa

rl/spec/box2d_experiment_specs.json
[lunar_dqn-2017_03_23_140002_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/871416/lunar_dqn-2017_03_23_140002_analysis_data.csv.zip)
[lunar_dqn-2017_03_23_140002_t42.json.zip](https://github.com/kengz/openai_lab/files/871417/lunar_dqn-2017_03_23_140002_t42.json.zip)
=> Solution: LunarLander-v2 with DQN

rl/spec/box2d_experiment_specs.json
[lunar_double_dqn-2017_03_25_224625_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/873905/lunar_double_dqn-2017_03_25_224625_analysis_data.csv.zip)
[lunar_double_dqn-2017_03_25_224625_t57.json.zip](https://github.com/kengz/openai_lab/files/873903/lunar_double_dqn-2017_03_25_224625_t57.json.zip)
=> Solution: LunarLander-v2 with double-DQN

rl/agent/deep_exp_sarsa.py, rl/agent/deep_sarsa.py, rl/agent/offpol_sarsa.py, rl/analytics.py, rl/spec/classic_experiment_specs.json
=> Schedule sarsa and mountain

rl/spec/classic_experiment_specs.json
[offpol_sarsa-2017_03_28_132741_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/877897/offpol_sarsa-2017_03_28_132741_analysis_data.csv.zip)
[offpol_sarsa-2017_03_28_132741_t49.json.zip](https://github.com/kengz/openai_lab/files/877896/offpol_sarsa-2017_03_28_132741_t49.json.zip)
=> Solution: CartPole-v0 with OffPolicySarsa

rl/spec/box2d_experiment_specs.json, rl/spec/classic_experiment_specs.json
[acrobot-2017_03_27_123019_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/880992/acrobot-2017_03_27_123019_analysis_data.csv.zip)
[acrobot-2017_03_27_123019_t60.json.zip](https://github.com/kengz/openai_lab/files/880990/acrobot-2017_03_27_123019_t60.json.zip)
=> Solution: Acrobot-v1 with DQN

rl/spec/classic_experiment_specs.json
[rand_acrobot-2017_03_28_082754_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/881023/rand_acrobot-2017_03_28_082754_analysis_data.csv.zip)
[rand_acrobot-2017_03_28_082754_t9.json.zip](https://github.com/kengz/openai_lab/files/881021/rand_acrobot-2017_03_28_082754_t9.json.zip)
=> Solution: RandomSearch Acrobot-v1 with DQN

rl/spec/box2d_experiment_specs.json, test/test_basic.py
[lunar_offpol_sarsa-2017_03_30_072442_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/884297/lunar_offpol_sarsa-2017_03_30_072442_analysis_data.csv.zip)
[lunar_offpol_sarsa-2017_03_30_072442_t15.json.zip](https://github.com/kengz/openai_lab/files/884292/lunar_offpol_sarsa-2017_03_30_072442_t15.json.zip)
=> Solution: LunarLander-v2 with OffPolicySarsa

rl/spec/classic_experiment_specs.json
[acrobot_offpol_sarsa-2017_03_30_231202_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/886965/acrobot_offpol_sarsa-2017_03_30_231202_analysis_data.csv.zip)
[acrobot_offpol_sarsa-2017_03_30_231202_t9.json.zip](https://github.com/kengz/openai_lab/files/886964/acrobot_offpol_sarsa-2017_03_30_231202_t9.json.zip)
=> Solution: Acrobot-v1 with OffPolicySarsa

rl/spec/classic_experiment_specs.json
[rand_acrobot_double_dqn-2017_03_30_210911_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/886985/rand_acrobot_double_dqn-2017_03_30_210911_analysis_data.csv.zip)
[rand_acrobot_double_dqn-2017_03_30_210911_t4.json.zip](https://github.com/kengz/openai_lab/files/886981/rand_acrobot_double_dqn-2017_03_30_210911_t4.json.zip)
=> Solution: RandomSearch Acrobot-v1 with DoubleDQN

Gruntfile.js, rl/analytics.py, rl/experiment.py, rl/spec/classic_experiment_specs.json, rl/util.py
=> Generalize stability metric

rl/agent/ddpg.py, rl/agent/dqn.py, rl/experiment.py, rl/memory/base_memory.py, rl/memory/linear.py, rl/memory/prioritized_exp_replay.py, rl/memory/ranked.py, rl/preprocessor/atari.py, rl/preprocessor/base_preprocessor.py, rl/preprocessor/linear.py, rl/spec/atari_experiment_specs.json, rl/spec/classic_experiment_specs.json, rl/spec/dev_experiment_specs.json
Prioritized Memory Replay (PER)
=> Per memory

rl/experiment.py, rl/memory/base_memory.py, rl/memory/linear.py, rl/memory/prioritized_exp_replay.py, rl/memory/ranked.py, rl/spec/box2d_experiment_specs.json, rl/spec/classic_experiment_specs.json, test/test_basic.py
=> schedule mountain, ddqn-per, fix PER negative reward breakage

rl/spec/atari_experiment_specs.json
=> Use EpsilonGreedy for Atari

rl/spec/classic_experiment_specs.json
For audience to try out, in order of strength:
- Epsilon Greedy: `python3 main.py -e dqn_epsilon`
- Boltzmann: `python3 main.py -e dqn`
- Experience replay + Boltzmann: `python3 main.py -e dqn_per`
=> add specs for talk

rl/spec/classic_experiment_specs.json
_If you're contributing new algorithms and its solutions to OpenAI Lab, please follow below. Otherwise, clear below and concisely describe your commits._
=> Adding sarsa specs

rl/spec/classic_experiment_specs.json
[cartpole_ac_softmax-2017_04_10_091401_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/931749/cartpole_ac_softmax-2017_04_10_091401_analysis_data.csv.zip)
[cartpole_ac_softmax-2017_04_10_091401_t33.json.zip](https://github.com/kengz/openai_lab/files/931748/cartpole_ac_softmax-2017_04_10_091401_t33.json.zip)
=> Solution: CartPole-v0 with ActorCritic

rl/spec/classic_experiment_specs.json
[cartpole_v1_ac_softmax-2017_04_11_002020_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/931772/cartpole_v1_ac_softmax-2017_04_11_002020_analysis_data.csv.zip)
[cartpole_v1_ac_softmax-2017_04_11_002020_t28.json.zip](https://github.com/kengz/openai_lab/files/931771/cartpole_v1_ac_softmax-2017_04_11_002020_t28.json.zip)
=> Solution: CartPole-v1 with ActorCritic

rl/spec/classic_experiment_specs.json
[pendulum_ddpg-2017_04_18_084004_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/931784/pendulum_ddpg-2017_04_18_084004_analysis_data.csv.zip)
[pendulum_ddpg-2017_04_18_084004_t13.json.zip](https://github.com/kengz/openai_lab/files/931782/pendulum_ddpg-2017_04_18_084004_t13.json.zip)
=> Solution: Pendulum-v0 with DDPG

environment.yml, requirements.txt, rl/analytics.py, rl/util.py
- automatically zip the analysis csv file and best trial json for PR upload
- update gym installation to source from openai github
=> autozip files

rl/spec/classic_experiment_specs.json
[acrobot_ac_softmax-2017_04_11_231206_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/950411/acrobot_ac_softmax-2017_04_11_231206_analysis_data.csv.zip)
[acrobot_ac_softmax-2017_04_11_231206_t32.json.zip](https://github.com/kengz/openai_lab/files/950412/acrobot_ac_softmax-2017_04_11_231206_t32.json.zip)
=> Solution: Acrobot-v1 with ActorCritic

rl/spec/classic_experiment_specs.json
[pendulum_ddpg_per_linearnoise-2017_04_24_023940_analysis_data.csv.zip](https://github.com/kengz/openai_lab/files/951708/pendulum_ddpg_per_linearnoise-2017_04_24_023940_analysis_data.csv.zip)
[pendulum_ddpg_per_linearnoise-2017_04_24_023940_t3.json.zip](https://github.com/kengz/openai_lab/files/951710/pendulum_ddpg_per_linearnoise-2017_04_24_023940_t3.json.zip)
=> Solution: Pendulum-v0 with DDPG PrioritizedExperienceReplay LinearNoisePolicy
